### ISSUE TITLE
[GPRO] How to train model using vLLM and model parallelism?

### ISSUE THREAD

**Issue by zhiqihuang** [huggingface/trl#3424]
I tried to start GRPO trainer with vLLM and model parallelism on a single node with 8 GPUs (8 x A100 80G).

My plan was to use one GPU as the vLLM server and other 7 GPUs to load model with model parallelism (e.g., `device_map="auto"`)

```
CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model <model_path> &
CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 accelerate launch --num_machines 1 --num_processes 1 train.py
```

But the training ran into the following error

`AssertionError: this nccl communicator is created to work on cuda:0, but the input tensor is on cuda:1`

I think it happened when copying the weights to vLLM server.

**Comment by re-imagined** [comment]
Try to wait for the vLLM server to be ready before starting the training process. You can poll its health endpoint:
```
while ! curl --silent --fail http://0.0.0.0:8000/health/; do
  echo "Waiting for vLLM server…"
  sleep 1
done

# Once healthy, kick off your training:
python train.py

```

**Comment by shirinyamani** [comment]
@zhiqihuang thanks for trying it out! 
Have you tried setting the devices only for training ?
bc after we merged the support for dp, you would not need to set the devices for vllm but you need to set the devices for training. and making sure that they do no share device with one another. and if by model parallelism you mean tensor-parallalism it should be fine to use!

We provided a complete doc based on the additions (tp+dp) and the way one can use it here [vllm-integration](https://huggingface.co/docs/trl/main/en/vllm_integration)

**Comment by zhiqihuang** [comment]
> [@zhiqihuang](https://github.com/zhiqihuang) thanks for trying it out! Have you tried setting the devices only for training ? bc after we merged the support for dp, you would not need to set the devices for vllm but you need to set the devices for training. and making sure that they do no share device with one another. and if by model parallelism you mean tensor-parallalism it should be fine to use!
> 
> We provided a complete doc based on the additions (tp+dp) and the way one can use it here [vllm-integration](https://huggingface.co/docs/trl/main/en/vllm_integration)

Thank you very much for replying.

Actually the vllm-server is up and running. The issue is model parallelism on the trainer side.

To train a 8B (or even larger) model, instead of doing data parallelism, I want to do model parallelism which means split layers in to 7 GPUs so that each GPU only gets a part of the model. I load the model with `device_map="auto"`

```
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
```

But the training ran into the following error

```
  File "/home/jovyan/conda/envs/vllm/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 932, in _generate_and_score_completions
    self._move_model_to_vllm()
  File "/home/jovyan/conda/envs/vllm/lib/python3.12/site-packages/trl/extras/profiling.py", line 87, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda/envs/vllm/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 872, in _move_model_to_vllm
    self.vllm_client.update_named_param(name, param.data)
  File "/home/jovyan/conda/envs/vllm/lib/python3.12/site-packages/trl/extras/vllm_client.py", line 244, in update_named_param
    self.pynccl_comm.broadcast(weights, src=self.rank)
  File "/home/jovyan/conda/envs/vllm/lib/python3.12/site-packages/vllm/distributed/device_communicators/pynccl.py", line 203, in broadcast
    assert tensor.device == self.device, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: this nccl communicator is created to work on cuda:0, but the input tensor is on cuda:1
```

Not sure how to adjust the trainer.

**Comment by zhiqihuang** [comment]
Update:

I think the error is cause by starting PyNcclCommunicator at device 0, see [here](https://github.com/huggingface/trl/blob/cd6b3de356dd03025640681aaad7b45a1574d92f/trl/extras/vllm_client.py#L222C28-L222C46)

But when updating params, there are layers from other GPU, so the [broadcast](https://github.com/vllm-project/vllm/blob/0189a65a2e76b94ee4cc872dbad2b732256e0e9a/vllm/distributed/device_communicators/pynccl.py#L203) failed because the input tensor and the PyNcclCommunicator is not on the same device. 

Not sure how to solve it tho.

**Comment by LRC-bit** [comment]
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16,
)
you need to delete "device_map="auto"", this is not design for deepspeed.

**Comment by cmunley1** [comment]
@zhiqihuang I am having the same issue, removing device_map auto did not solve it, did you find a solution? I am following the guide here: https://huggingface.co/docs/trl/main/en/vllm_integration but having the same issues as you described.

**Comment by qgallouedec** [comment]
Hey @zhiqihuang, sorry for the very slow reply here, we're catching up on the backlog.

Short answer: naive model parallelism via `device_map="auto"` isn't the supported way to train a model that's too big for one GPU with GRPO + vLLM, and it can't compose with the weight-sync path. The NCCL communicator in `VLLMClient` is created for a single device, so when `device_map="auto"` scatters parameters across cuda:1…cuda:6 the weight broadcast asserts — exactly the `nccl communicator is created to work on cuda:0, but the input tensor is on cuda:1` you saw. That's why current TRL explicitly forces `device_map=None` under multi-GPU / DeepSpeed launches: https://github.com/huggingface/trl/blob/82f6b2c9cf5313bb85c3d3c473cf2a4e527e76d7/trl/trainer/grpo_trainer.py#L341-L343

To shard a large model across your training GPUs, use DeepSpeed ZeRO-3 or FSDP (the trainer gathers each full parameter before broadcasting it to vLLM) and let the vLLM server do its own sharding via `--tensor-parallel-size`. So instead of `accelerate launch --num_processes 1` + `device_map="auto"`, run e.g. `CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 accelerate launch --config_file deepspeed_zero3.yaml --num_processes 7 train.py` with the server on GPU 0. See the vLLM integration and distributing-training docs. Closing as expected behavior rather than a bug — happy to help if ZeRO-3/FSDP still gives you trouble.

@cmunley1 if you dropped `device_map="auto"`, used dedicated GPUs for the server vs. training, and still hit the same assertion, that's most likely a different root cause; please open a fresh issue with your exact launch command and `trl env` output and we'll dig in.

Also as a pointer, check AsyncGRPO trainer, which might be more suitable for what you do.
