### ISSUE TITLE
CI fails with dev dependencies: HFValidationError: Repo id must use alphanumeric chars

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/trl#4323]
CI fails with dev dependencies: https://github.com/huggingface/trl/actions/runs/18712033739/job/53362520844
> huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.

Multiple tests:
```python
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm[trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm[trl-internal-testing/tiny-Qwen2VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm_beta_non_zero - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm_peft - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm_and_importance_sampling - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm_and_liger - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_grpo_trainer.py::TestGRPOTrainer::test_training_vlm_multi_image - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_rloo_trainer.py::TestRLOOTrainer::test_training_vlm[trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_rloo_trainer.py::TestRLOOTrainer::test_training_vlm[trl-internal-testing/tiny-Qwen2VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_sft_trainer.py::TestSFTTrainer::test_train_vlm[trl-internal-testing/tiny-Qwen2VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_rloo_trainer.py::TestRLOOTrainer::test_training_vlm_beta_non_zero - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_sft_trainer.py::TestSFTTrainer::test_train_vlm[trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration] - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_rloo_trainer.py::TestRLOOTrainer::test_training_vlm_peft - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_sft_trainer.py::TestSFTTrainer::test_train_vlm_multi_image - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_rloo_trainer.py::TestRLOOTrainer::test_training_vlm_multi_image - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_sft_trainer.py::TestSFTTrainer::test_train_vlm_prompt_completion - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  FAILED tests/test_sft_trainer.py::TestSFTTrainer::test_train_vlm_text_only_data - huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
```

Stacktrace:
```python
_ TestGRPOTrainer.test_training_vlm[trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration] _
  [gw3] linux -- Python 3.12.12 /__w/trl/trl/.venv/bin/python3
  
  path_or_repo_id = '', filenames = ['processor_config.json']
  cache_dir = '/github/home/.cache/huggingface/hub', force_download = False
  proxies = None, token = None, revision = None, local_files_only = False
  subfolder = '', repo_type = None
  user_agent = 'transformers/5.0.0.dev0; python/3.12.12; session_id/2047a935e364492090f99c27947a738f; torch/2.9.0'
  _raise_exceptions_for_gated_repo = False
  _raise_exceptions_for_missing_entries = False
  _raise_exceptions_for_connection_errors = False, _commit_hash = None
  deprecated_kwargs = {}, full_filenames = ['processor_config.json']
  existing_files = [], filename = 'processor_config.json', file_counter = 0
  
      def cached_files(
          path_or_repo_id: str | os.PathLike,
          filenames: list[str],
          cache_dir: str | os.PathLike | None = None,
          force_download: bool = False,
          proxies: dict[str, str] | None = None,
          token: bool | str | None = None,
          revision: str | None = None,
          local_files_only: bool = False,
          subfolder: str = "",
          repo_type: str | None = None,
          user_agent: str | dict[str, str] | None = None,
          _raise_exceptions_for_gated_repo: bool = True,
          _raise_exceptions_for_missing_entries: bool = True,
          _raise_exceptions_for_connection_errors: bool = True,
          _commit_hash: str | None = None,
          **deprecated_kwargs,
      ) -> str | None:
          """
          Tries to locate several files in a local folder and repo, downloads and cache them if necessary.
      
          Args:
              path_or_repo_id (`str` or `os.PathLike`):
                  This can be either:
                  - a string, the *model id* of a model repo on huggingface.co.
                  - a path to a *directory* potentially containing the file.
              filenames (`list[str]`):
                  The name of all the files to locate in `path_or_repo`.
              cache_dir (`str` or `os.PathLike`, *optional*):
                  Path to a directory in which a downloaded pretrained model configuration should be cached if the standard
                  cache should not be used.
              force_download (`bool`, *optional*, defaults to `False`):
                  Whether or not to force to (re-)download the configuration files and override the cached versions if they
                  exist.
              proxies (`dict[str, str]`, *optional*):
                  A dictionary of proxy servers to use by protocol or endpoint, e.g., `{'http': 'foo.bar:3128',
                  'http://hostname': 'foo.bar:4012'}.` The proxies are used on each request.
              token (`str` or *bool*, *optional*):
                  The token to use as HTTP bearer authorization for remote files. If `True`, will use the token generated
                  when running `hf auth login` (stored in `~/.huggingface`).
              revision (`str`, *optional*, defaults to `"main"`):
                  The specific model version to use. It can be a branch name, a tag name, or a commit id, since we use a
                  git-based system for storing models and other artifacts on huggingface.co, so `revision` can be any
                  identifier allowed by git.
              local_files_only (`bool`, *optional*, defaults to `False`):
                  If `True`, will only try to load the tokenizer configuration from local files.
              subfolder (`str`, *optional*, defaults to `""`):
                  In case the relevant files are located inside a subfolder of the model repo on huggingface.co, you can
                  specify the folder name here.
              repo_type (`str`, *optional*):
                  Specify the repo type (useful when downloading from a space for instance).
      
          Private args:
              _raise_exceptions_for_gated_repo (`bool`):
                  if False, do not raise an exception for gated repo error but return None.
              _raise_exceptions_for_missing_entries (`bool`):
                  if False, do not raise an exception for missing entries but return None.
              _raise_exceptions_for_connection_errors (`bool`):
                  if False, do not raise an exception for connection errors but return None.
              _commit_hash (`str`, *optional*):
                  passed when we are chaining several calls to various files (e.g. when loading a tokenizer or
                  a pipeline). If files are cached for this commit hash, avoid calls to head and get from the cache.
      
          <Tip>
      
          Passing `token=True` is required when you want to use a private model.
      
          </Tip>
      
          Returns:
              `Optional[str]`: Returns the resolved file (to the cache folder if downloaded from a repo).
      
          Examples:
      
          ```python
          # Download a model weight from the Hub and cache it.
          model_weights_file = cached_file("google-bert/bert-base-uncased", "pytorch_model.bin")
          ```
          """
          if is_offline_mode() and not local_files_only:
              logger.info("Offline mode: forcing local_files_only=True")
              local_files_only = True
          if subfolder is None:
              subfolder = ""
      
          # Add folder to filenames
          full_filenames = [os.path.join(subfolder, file) for file in filenames]
      
          path_or_repo_id = str(path_or_repo_id)
          existing_files = []
          for filename in full_filenames:
              if os.path.isdir(path_or_repo_id):
                  resolved_file = os.path.join(path_or_repo_id, filename)
                  if not os.path.isfile(resolved_file):
                      if _raise_exceptions_for_missing_entries and filename != os.path.join(subfolder, "config.json"):
                          revision_ = "main" if revision is None else revision
                          raise OSError(
                              f"{path_or_repo_id} does not appear to have a file named {filename}. Checkout "
                              f"'[https://huggingface.co/{path_or_repo_id}/tree/{revision_}](https://huggingface.co/%7Bpath_or_repo_id%7D/tree/%7Brevision_%7D)' for available files."
                          )
                      else:
                          continue
                  existing_files.append(resolved_file)
      
          if os.path.isdir(path_or_repo_id):
              return existing_files if existing_files else None
      
          if cache_dir is None:
              cache_dir = TRANSFORMERS_CACHE
          if isinstance(cache_dir, Path):
              cache_dir = str(cache_dir)
      
          existing_files = []
          file_counter = 0
          if _commit_hash is not None and not force_download:
              for filename in full_filenames:
                  # If the file is cached under that commit hash, we return it directly.
                  resolved_file = try_to_load_from_cache(
                      path_or_repo_id, filename, cache_dir=cache_dir, revision=_commit_hash, repo_type=repo_type
                  )
                  if resolved_file is not None:
                      if resolved_file is not _CACHED_NO_EXIST:
                          file_counter += 1
                          existing_files.append(resolved_file)
                      elif not _raise_exceptions_for_missing_entries:
                          file_counter += 1
                      else:
                          raise OSError(f"Could not locate {filename} inside {path_or_repo_id}.")
      
          # Either all the files were found, or some were _CACHED_NO_EXIST but we do not raise for missing entries
          if file_counter == len(full_filenames):
              return existing_files if len(existing_files) > 0 else None
      
          user_agent = http_user_agent(user_agent)
          # download the files if needed
          try:
              if len(full_filenames) == 1:
                  # This is slightly better for only 1 file
  >               hf_hub_download(
                      path_or_repo_id,
                      filenames[0],
                      subfolder=None if len(subfolder) == 0 else subfolder,
                      repo_type=repo_type,
                      revision=revision,
                      cache_dir=cache_dir,
                      user_agent=user_agent,
                      force_download=force_download,
                      proxies=proxies,
                      token=token,
                      local_files_only=local_files_only,
                  )
  
  .venv/lib/python3.12/site-packages/transformers/utils/hub.py:469: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  .venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py:85: in _inner_fn
      validate_repo_id(arg_value)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  repo_id = ''
  
      def validate_repo_id(repo_id: str) -> None:
          """Validate `repo_id` is valid.
      
          This is not meant to replace the proper validation made on the Hub but rather to
          avoid local inconsistencies whenever possible (example: passing `repo_type` in the
          `repo_id` is forbidden).
      
          Rules:
          - Between 1 and 96 characters.
          - Either "repo_name" or "namespace/repo_name"
          - [a-zA-Z0-9] or "-", "_", "."
          - "--" and ".." are forbidden
      
          Valid: `"foo"`, `"foo/bar"`, `"123"`, `"Foo-BAR_foo.bar123"`
      
          Not valid: `"datasets/foo/bar"`, `".repo_id"`, `"foo--bar"`, `"foo.git"`
      
          Example:
          ```py
          >>> from huggingface_hub.utils import validate_repo_id
          >>> validate_repo_id(repo_id="valid_repo_id")
          >>> validate_repo_id(repo_id="other..repo..id")
          huggingface_hub.utils._validators.HFValidationError: Cannot have -- or .. in repo_id: 'other..repo..id'.
          ```
      
          Discussed in https://github.com/huggingface/huggingface_hub/issues/1008.
          In moon-landing (internal repository):
          - https://github.com/huggingface/moon-landing/blob/main/server/lib/Names.ts#L27
          - https://github.com/huggingface/moon-landing/blob/main/server/views/components/NewRepoForm/NewRepoForm.svelte#L138
          """
          if not isinstance(repo_id, str):
              # Typically, a Path is not a repo_id
              raise HFValidationError(f"Repo id must be a string, not {type(repo_id)}: '{repo_id}'.")
      
          if repo_id.count("/") > 1:
              raise HFValidationError(
                  "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
                  f" '{repo_id}'. Use `repo_type` argument if needed."
              )
      
          if not REPO_ID_REGEX.match(repo_id):
  >           raise HFValidationError(
                  "Repo id must use alphanumeric chars, '-', '_' or '.'."
                  " The name cannot start or end with '-' or '.' and the maximum length is 96:"
                  f" '{repo_id}'."
              )
  E           huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  
  .venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py:135: HFValidationError
  
  During handling of the above exception, another exception occurred:
  
  self = <tests.test_grpo_trainer.TestGRPOTrainer object at 0x7fe900d1c470>
  model_id = 'trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration'
  
      @pytest.mark.parametrize(
          "model_id",
          [
              "trl-internal-testing/tiny-Gemma3ForConditionalGeneration",
              "trl-internal-testing/tiny-LlavaNextForConditionalGeneration",
              "trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration",
              "trl-internal-testing/tiny-Qwen2VLForConditionalGeneration",
              # "trl-internal-testing/tiny-SmolVLMForConditionalGeneration", seems not to support bf16 properly
          ],
      )
      @require_vision
      def test_training_vlm(self, model_id):
          dataset = load_dataset("trl-internal-testing/zen-image", "conversational_prompt_only", split="train")
      
          def reward_func(completions, **kwargs):
              """Reward function that rewards longer completions."""
              return [float(len(completion[0]["content"])) for completion in completions]
      
          training_args = GRPOConfig(
              output_dir=self.tmp_dir,
              learning_rate=0.1,  # increase the learning rate to speed up the test
              per_device_train_batch_size=3,  # reduce the batch size to reduce memory usage
              num_generations=3,  # reduce the number of generations to reduce memory usage
              max_completion_length=8,  # reduce the completion length to reduce memory usage
              max_prompt_length=None,  # disable prompt truncation, because usually, models don't support it
              report_to="none",
          )
  >       trainer = GRPOTrainer(
              model=model_id,
              reward_funcs=reward_func,
              args=training_args,
              train_dataset=dataset,
          )
  
  tests/test_grpo_trainer.py:1279: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  trl/trainer/grpo_trainer.py:281: in __init__
      processing_class = AutoProcessor.from_pretrained(model.config._name_or_path, truncation_side="left")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  .venv/lib/python3.12/site-packages/transformers/models/auto/processing_auto.py:287: in from_pretrained
      processor_config_file = cached_file(pretrained_model_name_or_path, PROCESSOR_NAME, **cached_file_kwargs)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  .venv/lib/python3.12/site-packages/transformers/utils/hub.py:326: in cached_file
      file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  .venv/lib/python3.12/site-packages/transformers/utils/hub.py:520: in cached_files
      _get_cache_file_to_return(path_or_repo_id, filename, cache_dir, revision, repo_type)
  .venv/lib/python3.12/site-packages/transformers/utils/hub.py:152: in _get_cache_file_to_return
      resolved_file = try_to_load_from_cache(
  .venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py:85: in _inner_fn
      validate_repo_id(arg_value)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  repo_id = ''
  
      def validate_repo_id(repo_id: str) -> None:
          """Validate `repo_id` is valid.
      
          This is not meant to replace the proper validation made on the Hub but rather to
          avoid local inconsistencies whenever possible (example: passing `repo_type` in the
          `repo_id` is forbidden).
      
          Rules:
          - Between 1 and 96 characters.
          - Either "repo_name" or "namespace/repo_name"
          - [a-zA-Z0-9] or "-", "_", "."
          - "--" and ".." are forbidden
      
          Valid: `"foo"`, `"foo/bar"`, `"123"`, `"Foo-BAR_foo.bar123"`
      
          Not valid: `"datasets/foo/bar"`, `".repo_id"`, `"foo--bar"`, `"foo.git"`
      
          Example:
          ```py
          >>> from huggingface_hub.utils import validate_repo_id
          >>> validate_repo_id(repo_id="valid_repo_id")
          >>> validate_repo_id(repo_id="other..repo..id")
          huggingface_hub.utils._validators.HFValidationError: Cannot have -- or .. in repo_id: 'other..repo..id'.
          ```
      
          Discussed in https://github.com/huggingface/huggingface_hub/issues/1008.
          In moon-landing (internal repository):
          - https://github.com/huggingface/moon-landing/blob/main/server/lib/Names.ts#L27
          - https://github.com/huggingface/moon-landing/blob/main/server/views/components/NewRepoForm/NewRepoForm.svelte#L138
          """
          if not isinstance(repo_id, str):
              # Typically, a Path is not a repo_id
              raise HFValidationError(f"Repo id must be a string, not {type(repo_id)}: '{repo_id}'.")
      
          if repo_id.count("/") > 1:
              raise HFValidationError(
                  "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
                  f" '{repo_id}'. Use `repo_type` argument if needed."
              )
      
          if not REPO_ID_REGEX.match(repo_id):
  >           raise HFValidationError(
                  "Repo id must use alphanumeric chars, '-', '_' or '.'."
                  " The name cannot start or end with '-' or '.' and the maximum length is 96:"
                  f" '{repo_id}'."
              )
  E           huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: ''.
  
  .venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py:135: HFValidationError
```

**Comment by albertvillanova** [comment]
After investigation, it seems the issue appeared after `transformers` merged this PR:
- https://github.com/huggingface/transformers/pull/41758 

CC: @zucchini-nlp, who reviewed that PR

Is there something we should fix on our side? For example, in:
```python
processing_class = AutoProcessor.from_pretrained(model.config._name_or_path, truncation_side="left")
```

**Comment by albertvillanova** [comment]
After further investigation, I think our tiny models may need being fixed.

Currently:
```python
In [2]: config = AutoConfig.from_pretrained("trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration")

In [3]: config._name_or_path
Out[3]: ''

In [4]: config.text_config._name_or_path
Out[4]: 'trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration'
```

**Comment by albertvillanova** [comment]
Oh, I just noticed that the original Qwen VL models have the same issue!

```python
for model_id in ["Qwen/Qwen2-VL-2B", "Qwen/Qwen2.5-VL-3B-Instruct"]:
    config = AutoConfig.from_pretrained(model_id)
    assert config._name_or_path == ""
    assert config.text_config._name_or_path == model_id
    assert config.vision_config._name_or_path == ""
```

@zucchini-nlp any suggestion on how to handle this situation?

**Comment by qgallouedec** [comment]
it means that most VLM can't be trained with transformers dev, right?

**Comment by albertvillanova** [comment]
Well, it depends on how many VL models have the issue above.

For the moment, it seems the issue is present only in Qwen2-VL and Qwen2.5-VL:
```python
Qwen/Qwen2-VL-2B-Instruct
config._name_or_path=''
config.text_config._name_or_path='Qwen/Qwen2-VL-2B-Instruct'
config.vision_config._name_or_path=''

Qwen/Qwen2.5-VL-3B-Instruct
config._name_or_path=''
config.text_config._name_or_path='Qwen/Qwen2.5-VL-3B-Instruct'
config.vision_config._name_or_path=''
```

I have checked other models and they seem to be OK:
```python
google/gemma-3-4b-it
config._name_or_path='google/gemma-3-4b-it'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''

google/paligemma-3b-pt-224
config._name_or_path='google/paligemma-3b-pt-224'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''

HuggingFaceM4/idefics2-8b
config._name_or_path='HuggingFaceM4/idefics2-8b'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''

HuggingFaceM4/Idefics3-8B-Llama3
config._name_or_path='HuggingFaceM4/Idefics3-8B-Llama3'
config.text_config._name_or_path='None'
config.vision_config._name_or_path=''

HuggingFaceTB/SmolVLM2-2.2B-Instruct
config._name_or_path='HuggingFaceTB/SmolVLM2-2.2B-Instruct'
config.text_config._name_or_path='None'
config.vision_config._name_or_path=''

llava-hf/llava-1.5-7b-hf
config._name_or_path='llava-hf/llava-1.5-7b-hf'
config.text_config._name_or_path='lmsys/vicuna-7b-v1.5'
config.vision_config._name_or_path=''

llava-hf/llava-v1.6-mistral-7b-hf
config._name_or_path='llava-hf/llava-v1.6-mistral-7b-hf'
config.text_config._name_or_path='mistralai/Mistral-7B-Instruct-v0.2'
config.vision_config._name_or_path=''

OpenGVLab/InternVL3-8B-hf
config._name_or_path='OpenGVLab/InternVL3-8B-hf'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''
```

**Comment by albertvillanova** [comment]
I have checked that Qwen3-VL models have been fixed:
```python
Qwen/Qwen3-VL-2B-Instruct
config._name_or_path='Qwen/Qwen3-VL-2B-Instruct'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''

Qwen/Qwen3-VL-2B-Thinking
config._name_or_path='Qwen/Qwen3-VL-2B-Thinking'
config.text_config._name_or_path=''
config.vision_config._name_or_path=''
```

**Comment by zucchini-nlp** [comment]
Made a quick PR in https://github.com/huggingface/transformers/pull/41808. The PR missed to update the `__setattr__` as well in the same way
I am off starting today so if the PR solves your tests, feel free to approve and merge :)

**Comment by albertvillanova** [comment]
Thanks a lot for your reactivity and fast proposed fix, @zucchini-nlp! 🤗 

Unfortunately, I have run our CI using your PR branch, and the problem persists. 

Indeed, I have investigated why and this is what I get when using your fix: 
- now both `config._name_or_path` and `config.text_config._name_or_path` are empty for Qwen2-VL and Qwen2.5-VL
```python
Qwen/Qwen2-VL-2B
config._name_or_path=''
config.text_config._name_or_path=''
config.vision_config._name_or_path=''

Qwen/Qwen2.5-VL-3B-Instruct
config._name_or_path=''
config.text_config._name_or_path=''
config.vision_config._name_or_path=''
```

**Comment by zucchini-nlp** [comment]
I am back from vacation today and will take a proper look at it, if it wasn't yet solved

Update, the fix works for me with the following script. Can you check transformers is installed from the correct branch?

```python
from transformers import AutoConfig, AutoProcessor

config = AutoConfig.from_pretrained("trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration")
processing_class = AutoProcessor.from_pretrained(config._name_or_path, truncation_side="left")

print(config._name_or_path)
```

**Comment by albertvillanova** [comment]
Welcome back, @zucchini-nlp. I hope you enjoyed your vacation! 🤗 

I have tried again, and the problem persists on my side:
- Not for "trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration", where I get the same result as you
- But for "Qwen/Qwen2-VL" and "Qwen/Qwen2.5-VL", where I get the empty string for `_name_or_path` at both the root config and at the text_config levels

Could you please try this code snippet?

```shell
rm -fr ~/.cache/huggingface/hub/models--trl-internal-testing--tiny-Qwen2_5_VLForConditionalGeneration
rm -fr ~/.cache/huggingface/hub/models--Qwen--Qwen2.5-VL-3B-Instruct
rm -fr ~/.cache/huggingface/hub/models--Qwen--Qwen2-VL-2B-Instruct
rm -fr ~/.cache/huggingface/hub/models--Qwen--Qwen2-VL-2B
```
```python
from transformers import AutoConfig

for model_id in [
    "trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration",
    "Qwen/Qwen2.5-VL-3B-Instruct",
    "Qwen/Qwen2-VL-2B-Instruct",
    "Qwen/Qwen2-VL-2B"
]:
    config = AutoConfig.from_pretrained(model_id)
    print(model_id)
    print(f"{config._name_or_path=}")
    print(f"{config.text_config._name_or_path=}")
    print()
```
```python
trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration
config._name_or_path='Qwen/Qwen2.5-VL-3B-Instruct'
config.text_config._name_or_path='Qwen/Qwen2.5-VL-3B-Instruct'

Qwen/Qwen2.5-VL-3B-Instruct
config._name_or_path=''
config.text_config._name_or_path=''

Qwen/Qwen2-VL-2B-Instruct
config._name_or_path=''
config.text_config._name_or_path=''

Qwen/Qwen2-VL-2B
config._name_or_path=''
config.text_config._name_or_path=''
```

**Comment by albertvillanova** [comment]
Note that "trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration" was recently updated by @kashif and he explicitly added the `_name_or_path` value to the config file: https://huggingface.co/trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration/commit/b0b270136b9dadda4990d57c66f315d4d3f5597c

However, I think we should revert that specific line of the config: IMO, the `_name_or_path` should not be serialized to the config.json file, as it is the case for the rest of the models, also for "trl-internal-testing/tiny-Qwen2VLForConditionalGeneration":
```python
model_id = "trl-internal-testing/tiny-Qwen2VLForConditionalGeneration"
config = AutoConfig.from_pretrained(model_id)
print(model_id)
print(f"{config._name_or_path=}")
print(f"{config.text_config._name_or_path=}")
```
```python
trl-internal-testing/tiny-Qwen2VLForConditionalGeneration
config._name_or_path=''
config.text_config._name_or_path=''
```

**Comment by zucchini-nlp** [comment]
Oh, didn't know that repo was updated manually. I merged the fix and tried on latest main with official checkpoint, which weren't updated. I got the `_name_and_path` for the model after loading and it looks similar to other VLM's outputs. And I agree that they should not be serialized in config file

```python
from transformers import AutoConfig

model_id = "Qwen/Qwen2.5-VL-3B-Instruct"
config = AutoConfig.from_pretrained(model_id)
print(model_id)
print(f"{config._name_or_path=}") 
print(f"{config.text_config._name_or_path=}")

>>> config._name_or_path='Qwen/Qwen2.5-VL-3B-Instruct'
>>> config.text_config._name_or_path=''
```

**Comment by albertvillanova** [comment]
Fixed by https://github.com/huggingface/transformers/pull/41808.

Thanks for the fix, @zucchini-nlp! 🤗 
I have tested the main branch locally and it works as expected.
I have also reverted the hotfix on our side.

On the other hand, when trying to regenerate the tiny model (see: https://huggingface.co/trl-internal-testing/tiny-Qwen2_5_VLForConditionalGeneration/commit/b0b270136b9dadda4990d57c66f315d4d3f5597c) using the transformers main branch, I am getting a 'rope_theta' KeyError:
```python
  File "/huggingface/transformers/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 1376, in __init__
    self.model = Qwen2_5_VLModel(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 963, in __init__
    self.language_model = Qwen2_5_VLTextModel._from_config(config.text_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/modeling_utils.py", line 1468, in _from_config
    model = cls(config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 811, in __init__
    self.rotary_emb = Qwen2_5_VLRotaryEmbedding(config=config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 506, in __init__
    inv_freq, self.attention_scaling = rope_init_fn(self.config, device)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/huggingface/transformers/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 530, in compute_default_rope_parameters
    base = config.rope_parameters["rope_theta"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'rope_theta'
```
I guess this is caused after the merge of:
- https://github.com/huggingface/transformers/pull/39847

I am opening a separate issue to track this:
- #4583
